### ISSUE TITLE
Godot 4 compatibility

### ISSUE THREAD

**Issue by jamescarignan** [Arcweave/arcweave-godot-adventure-example#2]
I tried opening this project in Godot 4.1.3, and the built-in conversion doesn't fix nearly enough to get it working. Is there any chance the whole project can be updated to work with version 4?

**Comment by GiannisGG** [comment]
Hey there, thanks for the message. This is in fact the Godot 3 example. We have a different one for Godot 4 (a dungeon crawler thingy), which we haven't published yet, due to changes we are doing on the plugin side. (We are working on the Unreal, Unity, and Godot plugins at the same time and it takes a while...) Nevertheless, I can close a functioning version and update our git, and get back to you, hopefully by the end of the week.

EDIT 1: we currently have a version of this dungeon crawler that runs in Godot 4. 

EDIT 2: there is also the Castle demo game for Godot 4 [here](https://github.com/arcweave/arcweave-godot-playmode-example/tree/v2.x). Does this help as a demo?

**Comment by jamescarignan** [comment]
I appreciate the response! I just tried the Castle demo, and it looks to still be using i.e. File instead of FileAccess. I'm completely new to Godot, so I could be doing something wrong, but it wasn't running using 4.1.3. I'm able to run projects from the Asset Library though.

**Comment by GiannisGG** [comment]
Hey James, thanks for the patience regarding this aspect of Arcweave. I'll repeat myself saying that we're working on changing the plugins in Q1 of 2024, but you can make-do with the current demos in the meantime.

The Castle link I provide above actually runs in Godot 4—I just tried it with Godot 4.2. Are you sure the page is showing v2.x as its branch?

<img width="225" alt="image" src="https://github.com/arcweave/arcweave-godot-adventure-example/assets/9048496/3e2413bc-714c-4c25-a567-ff6e0b3c3a7e">

And I definitely see the use of FileAccess in it. Are you sure you've opened the right one?

<img width="779" alt="image" src="https://github.com/arcweave/arcweave-godot-adventure-example/assets/9048496/41687d6a-be9a-4fe5-89c3-72cab7fc0bda">

In any case, try this Godot 4 project: [CastleThe-ArcweaveDemo-Godot4.zip](https://github.com/arcweave/arcweave-godot-adventure-example/files/13682811/CastleThe-ArcweaveDemo-Godot4.zip). It may ask you to open it in Godot 4.2, though.

**Comment by jamescarignan** [comment]
Aha, I missed the branch requirement. Got it working, cheers!
